{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "11211ee7-fa6d-4ce6-b5d4-294e9370993f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter temperature:  30\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Low membership:    0\n",
      "Medium membership: 1.0\n",
      "High membership:   0\n",
      "\n",
      "Final Fan Speed: 50.00\n"
     ]
    }
   ],
   "source": [
    "# Fuzzy Logic: Temperature to Fan Speed\n",
    "def low_temp(x):\n",
    "    if x <= 20:\n",
    "        return 1\n",
    "    elif 20 < x < 30:\n",
    "        return (30 - x) / 10\n",
    "    else:\n",
    "        return 0\n",
    "def medium_temp(x):\n",
    "    if 20 < x < 30:\n",
    "        return (x - 20) / 10\n",
    "    elif 30 <= x <= 40:\n",
    "        return (40 - x) / 10\n",
    "    else:\n",
    "        return 0\n",
    "def high_temp(x):\n",
    "    if x <= 30:\n",
    "        return 0\n",
    "    elif 30 < x < 40:\n",
    "        return (x - 30) / 10\n",
    "    else:\n",
    "        return 1\n",
    "def fuzzy_logic(temp):\n",
    "  #Fuzzification\n",
    "    low = low_temp(temp)\n",
    "    medium = medium_temp(temp)\n",
    "    high = high_temp(temp)\n",
    "    print(f\"Low membership:    {low}\")\n",
    "    print(f\"Medium membership: {medium}\")\n",
    "    print(f\"High membership:   {high}\")\n",
    "    numerator = (low * 20) + (medium * 50) + (high * 80)\n",
    "    denominator = low + medium + high\n",
    "    if denominator == 0:\n",
    "        return 0\n",
    "    # Defuzzification\n",
    "    speed = numerator / denominator\n",
    "    return speed\n",
    "# Input\n",
    "temp = float(input(\"Enter temperature: \"))\n",
    "speed = fuzzy_logic(temp)\n",
    "print(f\"\\nFinal Fan Speed: {speed:.2f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "b629f246-4dbf-46a8-96c4-359e90fa6c09",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Alpha-cut: ['Medium', 'High']\n",
      "MOM: 3.0\n",
      "COG: 2.8000000000000003\n"
     ]
    }
   ],
   "source": [
    "## Defuzzification using Centroid Method\n",
    "def alpha_cut(fs, lam):\n",
    "    result = []\n",
    "    for k in fs:\n",
    "        if fs[k] >= lam:\n",
    "            result.append(k)\n",
    "    return result\n",
    "# Mean of Maximum (MOM)\n",
    "def mom(fs):\n",
    "    max_val = None\n",
    "    for k in fs:\n",
    "        if max_val is None or fs[k] > max_val:\n",
    "            max_val = fs[k]\n",
    "    total = 0\n",
    "    count = 0\n",
    "    for k in fs:\n",
    "        if fs[k] == max_val:\n",
    "            total += k\n",
    "            count += 1\n",
    "    return total / count\n",
    "def cog(fs):\n",
    "    numerator = 0\n",
    "    denominator = 0\n",
    "    for i in fs:\n",
    "        numerator += i*fs[i]\n",
    "        denominator += fs[i]\n",
    "    if denominator == 0:\n",
    "        return 0\n",
    "    return numerator / denominator\n",
    "# Example fuzzy output values\n",
    "fs1 = {\"Low\": 0.2, \"Medium\": 0.7, \"High\": 0.5}\n",
    "print(\"Alpha-cut:\", alpha_cut(fs1, 0.5))\n",
    "fs2 = {1:0.2, 2:0.5, 3:0.8, 4:0.5}\n",
    "print(\"MOM:\", mom(fs2))\n",
    "print(\"COG:\", cog(fs2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "ccdb9844-bfd6-466e-93e9-12389b8a0cda",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shortest Path Cost Found: 6\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "# 1. Setup (Example: 4 cities in a square)\n",
    "dist = np.array([[0, 2, 2, 1], [2, 0, 1, 2], [2, 1, 0, 2], [1, 2, 2, 0]])\n",
    "n = len(dist)\n",
    "pheromone = np.ones((n, n))\n",
    "num_ants, iterations = 10, 50\n",
    "alpha, beta, evap = 1, 2, 0.5\n",
    "best_cost = float('inf')\n",
    "for _ in range(iterations):\n",
    "    paths = []\n",
    "    for _ in range(num_ants):\n",
    "        path = [0] # All ants start at city 0\n",
    "        visited = {0}\n",
    "        while len(path) < n:\n",
    "            curr =#aco\n",
    "import numpy as np\n",
    "dist = np.array([[0, 2, 2, 1], [2, 0, 1, 2], [2, 1, 0, 2], [1, 2, 2, 0]])\n",
    "n = len(dist)\n",
    "num_ants = n\n",
    "iterations = 20\n",
    "alpha = 1        # pheromone importance\n",
    "beta = 2         # distance importance\n",
    "evaporation = 0.5\n",
    "pheromone = np.ones((n, n))\n",
    "def choose_next(current, unvisited):\n",
    "   probs = []\n",
    "   for j in unvisited:\n",
    "        tau = pheromone[current][j] ** alpha\n",
    "        eta = (1 / (dist[current][j] + 1e-10)) ** beta\n",
    "        probs.append(tau * eta)\n",
    "   probs = np.array(probs)\n",
    "   probs = probs / probs.sum()\n",
    "   return np.random.choice(unvisited, p=probs)\n",
    "   \n",
    "best_path = None\n",
    "best_cost = float('inf')\n",
    "for _ in range(iterations):\n",
    "    all_paths = []\n",
    "    for ant in range(num_ants):\n",
    "        visited = [False] * n\n",
    "        path = [0]\n",
    "        visited[0] = True\n",
    "        current = 0\n",
    "        cost = 0\n",
    "        # build path\n",
    "        for _ in range(n - 1):\n",
    "            unvisited = [j for j in range(n) if not visited[j]]\n",
    "            next_city = choose_next(current, unvisited)\n",
    "            cost += dist[current][next_city]\n",
    "            path.append(next_city)\n",
    "            visited[next_city] = True\n",
    "            current = next_city\n",
    "        # return to start\n",
    "        cost += dist[current][0]\n",
    "        path.append(0)\n",
    "        all_paths.append((path, cost))\n",
    "        # update global best\n",
    "        if cost < best_cost:\n",
    "            best_cost = cost\n",
    "            best_path = path\n",
    "    # -------------------------\n",
    "     # evaporation\n",
    "    pheromone *= (1 - evaporation)\n",
    "    # add new pheromone\n",
    "    for path, cost in all_paths:\n",
    "        for i in range(len(path) - 1):\n",
    "            a, b = path[i], path[i + 1]\n",
    "            pheromone[a][b] += 1 / cost\n",
    "# --------------------------\n",
    "# OUTPUT\n",
    "# --------------------------\n",
    "print(\"\\nBest Path:\", best_path)\n",
    "print(\"Best Cost:\", best_cost)m(probs)\n",
    "            # Choose next city and move\n",
    "            next_city = np.random.choice(unvisited, p=probs)\n",
    "            path.append(next_city)\n",
    "            visited.add(next_city)\n",
    "        # Calculate tour cost (including return to start)\n",
    "        cost = sum(dist[path[i]][path[i+1]] for i in range(n-1)) + dist[path[-1]][path[0]]\n",
    "        paths.append((path, cost))\n",
    "        if cost < best_cost: best_cost = cost\n",
    "    # Update Pheromones (Evaporate then Deposit)\n",
    "    pheromone *= (1 - evap)\n",
    "    for path, cost in paths:\n",
    "        for i in range(n-1):\n",
    "            pheromone[path[i]][path[i+1]] += 1/cost\n",
    "            pheromone[path[i+1]][path[i]] += 1/cost\n",
    "print(f\"Shortest Path Cost Found: {best_cost}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "fa0c04c4-4b49-4c56-9d99-0d61c8f97b9c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iteration 1: gBest = 1.6326, f(x) = 2.665277\n",
      "Iteration 2: gBest = -0.4569, f(x) = 0.20879\n",
      "Iteration 3: gBest = -0.4569, f(x) = 0.20879\n",
      "Iteration 4: gBest = -0.1911, f(x) = 0.036513\n",
      "Iteration 5: gBest = -0.1911, f(x) = 0.036513\n",
      "Iteration 6: gBest = -0.1911, f(x) = 0.036513\n",
      "Iteration 7: gBest = -0.0778, f(x) = 0.006059\n",
      "Iteration 8: gBest = -0.0752, f(x) = 0.005658\n",
      "Iteration 9: gBest = 0.0571, f(x) = 0.003257\n",
      "Iteration 10: gBest = -0.0284, f(x) = 0.000807\n",
      "\n",
      "Best Position (Solution): -0.0284\n",
      "Minimum Value: 0.0008\n"
     ]
    }
   ],
   "source": [
    "#pso\n",
    "import random\n",
    "# Objective function (minimize)\n",
    "def fitness(x):\n",
    "    return x**2\n",
    "# Parameters\n",
    "num_particles = 5\n",
    "iterations = 10\n",
    "w = 0.5       # inertia\n",
    "c1 = 1        # cognitive\n",
    "c2 = 2        # social\n",
    "# Initialize particles\n",
    "particles = [random.uniform(-10, 10) for _ in range(num_particles)]\n",
    "velocities = [random.uniform(-1, 1) for _ in range(num_particles)]\n",
    "pBest = particles[:]\n",
    "gBest = min(particles, key=fitness)\n",
    "for i in range(iterations):\n",
    "    for j in range(num_particles):\n",
    "        r1 = random.random()\n",
    "        r2 = random.random()\n",
    "        # Update velocity\n",
    "        velocities[j] = (w * velocities[j] +\n",
    "                         c1 * r1 * (pBest[j] - particles[j]) +\n",
    "                         c2 * r2 * (gBest - particles[j]))\n",
    "        # Update position\n",
    "        particles[j] += velocities[j]\n",
    "        # Update Pbest\n",
    "        if fitness(particles[j]) < fitness(pBest[j]):\n",
    "            pBest[j] = particles[j]\n",
    "    # Update Gbest\n",
    "    gBest = min(pBest, key=fitness)\n",
    "    print(f\"Iteration {i+1}: gBest = {round(gBest, 4)}, f(x) = {round(fitness(gBest), 6)}\")\n",
    "print(\"\\nBest Position (Solution):\", round(gBest, 4))   \n",
    "print(\"Minimum Value:\", round(fitness(gBest), 4))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6942372b-0e7b-44d5-be51-617398bc22e6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generation 1: [9, 8, 6, 5, 5, 2]\n",
      "Generation 2: [9, 8, 8, 6, 5, 5]\n",
      "Generation 3: [9, 8, 8, 8, 6, 5]\n",
      "Generation 4: [9, 9, 8, 8, 8, 6]\n",
      "Generation 5: [9, 9, 9, 8, 8, 8]\n",
      "Generation 6: [9, 9, 9, 9, 8, 8]\n",
      "Generation 7: [9, 9, 9, 9, 9, 8]\n",
      "Generation 8: [9, 9, 9, 9, 9, 9]\n",
      "Generation 9: [9, 9, 9, 9, 9, 9]\n",
      "Generation 10: [9, 9, 9, 9, 9, 9]\n",
      "Generation 11: [9, 9, 9, 9, 9, 9]\n",
      "Generation 12: [9, 9, 9, 9, 9, 9]\n",
      "Generation 13: [9, 9, 9, 9, 9, 9]\n",
      "Generation 14: [9, 9, 9, 9, 9, 9]\n",
      "Generation 15: [9, 9, 9, 9, 9, 9]\n",
      "Generation 16: [9, 9, 9, 9, 9, 7]\n",
      "Generation 17: [9, 9, 9, 9, 9, 9]\n",
      "Generation 18: [9, 9, 9, 9, 9, 9]\n",
      "Generation 19: [9, 9, 9, 9, 9, 9]\n",
      "Generation 20: [9, 9, 9, 9, 9, 9]\n",
      "\n",
      "===================================\n",
      "Best Solution: 9\n",
      "Maximum Value: 729\n",
      "===================================\n"
     ]
    }
   ],
   "source": [
    "##genetic algorithm\n",
    "import random\n",
    "# Fitness function (maximize)\n",
    "def fitness(x):\n",
    "    return x**3\n",
    "# Parameters\n",
    "population_size = 6\n",
    "generations = 20\n",
    "mutation_rate = 0.1\n",
    "# Initialize population (random integers)\n",
    "population = [random.randint(0, 10) for _ in range(population_size)]\n",
    "for gen in range(generations):\n",
    "    # Fitness Evaluation\n",
    "    population = sorted(population, key=fitness, reverse=True)\n",
    "    print(f\"Generation {gen+1}: {population}\")\n",
    "    # Selection (top 2)\n",
    "    parent1, parent2 = population[0], population[1]\n",
    "    # Crossover (simple average)\n",
    "    child = (parent1 + parent2) // 2\n",
    "    # Mutation\n",
    "    if random.random() < mutation_rate:\n",
    "        child += random.randint(-2, 2)\n",
    "    # Replace worst individual\n",
    "    population[-1] = child\n",
    "# Final result\n",
    "best = max(population, key=fitness)\n",
    "print(\"\\n\" + \"=\" * 35)\n",
    "print(\"Best Solution:\", best)\n",
    "print(\"Maximum Value:\", fitness(best))\n",
    "print(\"=\" * 35)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "00b1e2cb-25ef-48bf-b0a3-b104bf3a5d34",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iter  1 | Alpha:   1.8722 | Best f(x): 3.505275\n",
      "Iter  2 | Alpha:   1.5406 | Best f(x): 2.373358\n",
      "Iter  3 | Alpha:   2.5897 | Best f(x): 6.706360\n",
      "Iter  4 | Alpha:   1.8677 | Best f(x): 3.488165\n",
      "Iter  5 | Alpha:   2.9173 | Best f(x): 8.510368\n",
      "Iter  6 | Alpha:   2.0335 | Best f(x): 4.134999\n",
      "Iter  7 | Alpha:   2.5341 | Best f(x): 6.421421\n",
      "Iter  8 | Alpha:   2.3179 | Best f(x): 5.372553\n",
      "Iter  9 | Alpha:   1.9572 | Best f(x): 3.830524\n",
      "Iter 10 | Alpha:   1.8949 | Best f(x): 3.590626\n",
      "Iter 11 | Alpha:   2.1539 | Best f(x): 4.639422\n",
      "Iter 12 | Alpha:   1.6944 | Best f(x): 2.871003\n",
      "Iter 13 | Alpha:   1.3746 | Best f(x): 1.889463\n",
      "Iter 14 | Alpha:   1.2174 | Best f(x): 1.482178\n",
      "Iter 15 | Alpha:   1.1772 | Best f(x): 1.385854\n",
      "Iter 16 | Alpha:   1.0668 | Best f(x): 1.138149\n",
      "Iter 17 | Alpha:   0.9920 | Best f(x): 0.984133\n",
      "Iter 18 | Alpha:   0.9540 | Best f(x): 0.910134\n",
      "Iter 19 | Alpha:   0.8542 | Best f(x): 0.729573\n",
      "Iter 20 | Alpha:   0.8743 | Best f(x): 0.764377\n",
      "=============================================\n",
      "Best Position : 0.8743\n",
      "Minimum Value : 0.764377\n"
     ]
    }
   ],
   "source": [
    "import random #6. Grey wolf\n",
    "def fitness(x):\n",
    "    return x ** 2\n",
    "# Parameters\n",
    "WOLVES, ITERS = 5, 20\n",
    "wolves = [random.uniform(-10, 10) for _ in range(WOLVES)]\n",
    "for t in range(ITERS):\n",
    "    wolves.sort(key=fitness)\n",
    "    alpha, beta, delta = wolves[0], wolves[1], wolves[2]\n",
    "    a = 2 - 2 * (t / ITERS)  # decreases from 2 to 0\n",
    "    new_wolves = []\n",
    "    for w in wolves:\n",
    "        X_new = 0\n",
    "        for leader in [alpha, beta, delta]:\n",
    "            r1, r2 = random.random(), random.random()\n",
    "            A = 2 * a * r1 - a\n",
    "            C = 2 * r2\n",
    "            D = abs(C * leader - w)\n",
    "            X_new += leader - A * D\n",
    "        new_wolves.append(X_new / 3)\n",
    "    wolves = new_wolves\n",
    "    print(f\"Iter {t+1:2d} | Alpha: {round(alpha,4):8.4f} | Best f(x): {round(fitness(alpha),6):.6f}\")\n",
    "\n",
    "print(\"=\" * 45)\n",
    "print(f\"Best Position : {round(alpha, 4)}\")\n",
    "print(f\"Minimum Value : {round(fitness(alpha), 6)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "75012132-8f12-4120-a7d7-a98af7563bb6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best Path: [4, np.int64(3), np.int64(2), np.int64(1), np.int64(0)]\n",
      "Best Path: 5\n"
     ]
    }
   ],
   "source": [
    "#inteligent water droplet\n",
    "import numpy as np\n",
    "n = 5  # number of nodes\n",
    "soil = np.ones((n, n))  # initial soil\n",
    "def select_next(current, visited):\n",
    "    probs = []\n",
    "    for j in range(n):\n",
    "        if j not in visited:\n",
    "            probs.append(1 / soil[current][j])\n",
    "        else:\n",
    "            probs.append(0)\n",
    "    probs = np.array(probs)\n",
    "    probs = probs / probs.sum()\n",
    "    return np.random.choice(range(n), p=probs)\n",
    "best_path = []\n",
    "best_cost = float('inf')\n",
    "for _ in range(10):  # iterations\n",
    "    for i in range(n):\n",
    "        visited = [i]\n",
    "        current = i\n",
    "    while len(visited) < n:\n",
    "                nxt = select_next(current, visited)\n",
    "                soil[current][nxt] += 0.1  # update soil\n",
    "                visited.append(nxt)\n",
    "                current = nxt\n",
    "    cost = len(visited)\n",
    "    if cost < best_cost:\n",
    "        best_cost = cost\n",
    "        best_path = visited\n",
    "print(\"Best Path:\", best_path)\n",
    "print(\"Best Path:\", best_cost)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "f7ad5116-2129-449d-bc83-6a748c0e70e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Iter 20: 0.0786\n",
      "Best: 0.07863909040087225\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "def fitness(x):\n",
    "    return x**2  # minimize\n",
    "n = 5\n",
    "fireflies = np.random.rand(n)\n",
    "for _ in range(20):\n",
    "    for i in range(n):\n",
    "        for j in range(n):\n",
    "            if fitness(fireflies[j]) < fitness(fireflies[i]):\n",
    "                r = abs(fireflies[i] - fireflies[j])\n",
    "                beta = 1 / (1 + r**2)\n",
    "                fireflies[i] += beta * (fireflies[j] - fireflies[i]) + np.random.rand()*0.1\n",
    "    best = min(fireflies, key=fitness)\n",
    "    print(f\"Iter {t+1}: {best:.4f}\")\n",
    "best = fireflies[np.argmin([fitness(x) for x in fireflies])]\n",
    "print(\"Best:\", best)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "6b9b9602-3c2c-47c5-8d14-fa4ff5aa6ed8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iter 1: -0.1046\n",
      "Iter 2: 0.0044\n",
      "Iter 3: 0.0044\n",
      "Iter 4: 0.0044\n",
      "Iter 5: -0.0132\n",
      "Iter 6: -0.0132\n",
      "Iter 7: -0.0132\n",
      "Iter 8: 0.0056\n",
      "Iter 9: 0.0056\n",
      "Iter 10: 0.0056\n",
      "Iter 11: 0.0001\n",
      "Iter 12: 0.0001\n",
      "Iter 13: 0.0001\n",
      "Iter 14: 0.0001\n",
      "Iter 15: 0.0001\n",
      "Iter 16: 0.0001\n",
      "Iter 17: 0.0000\n",
      "Iter 18: 0.0000\n",
      "Iter 19: 0.0000\n",
      "Iter 20: 0.0000\n",
      "the best is  2.7433003354664955e-06\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "def fitness(x): return x**2\n",
    "# Parameters\n",
    "S = 5          # Food sources\n",
    "limit = 10     # Max failures before abandonment\n",
    "iterations = 20\n",
    "food_sources = [random.uniform(-10, 10) for _ in range(S)]\n",
    "trials = [0] * S  # Counter for Scout phase\n",
    "\n",
    "for t in range(iterations):\n",
    "    # 1. EMPLOYED BEE PHASE\n",
    "    for i in range(S):\n",
    "        k = random.choice([n for n in range(S) if n != i])\n",
    "        new_sol = food_sources[i] + random.uniform(-1, 1) * (food_sources[i] - food_sources[k])\n",
    "        if fitness(new_sol) < fitness(food_sources[i]):\n",
    "            food_sources[i], trials[i] = new_sol, 0\n",
    "        else:\n",
    "            trials[i] += 1\n",
    "\n",
    "    # 2. ONLOOKER BEE PHASE (Based on Probability)\n",
    "    # Calculate fitness (Inverse of fitness for minimization)\n",
    "    fitness_vals = [1/(1+fitness(x)) if fitness(x)>=0 else 1+abs(fitness(x)) for x in food_sources]\n",
    "    prob = [f/sum(fitness_vals) for f in fitness_vals]\n",
    "    \n",
    "    for _ in range(S):\n",
    "        i = random.choices(range(S), weights=prob)[0] # Better sources chosen more\n",
    "        k = random.choice([n for n in range(S) if n != i])\n",
    "        new_sol = food_sources[i] + random.uniform(-1, 1) * (food_sources[i] - food_sources[k])\n",
    "        if fitness(new_sol) < fitness(food_sources[i]):\n",
    "            food_sources[i], trials[i] = new_sol, 0\n",
    "        else:\n",
    "            trials[i] += 1\n",
    "\n",
    "    # 3. SCOUT BEE PHASE\n",
    "    for i in range(S):\n",
    "        if trials[i] > limit:\n",
    "            food_sources[i] = random.uniform(-10, 10)\n",
    "            trials[i] = 0\n",
    "\n",
    "    best = min(food_sources, key=fitness)\n",
    "    print(f\"Iter {t+1}: {best:.4f}\")\n",
    "print(\"the best is \",best)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "b1b1a263-6c95-458e-8b39-e78ea7195814",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ABC] Iter  1 | Best position: 0.6014 | Minimum value: 0.3617\n",
      "[ABC] Iter  2 | Best position: 0.6014 | Minimum value: 0.3617\n",
      "[ABC] Iter  3 | Best position: -0.4000 | Minimum value: 0.1600\n",
      "[ABC] Iter  4 | Best position: -0.4000 | Minimum value: 0.1600\n",
      "[ABC] Iter  5 | Best position: 0.1192 | Minimum value: 0.0142\n",
      "[ABC] Iter  6 | Best position: 0.0264 | Minimum value: 0.0007\n",
      "[ABC] Iter  7 | Best position: 0.0264 | Minimum value: 0.0007\n",
      "[ABC] Iter  8 | Best position: 0.0264 | Minimum value: 0.0007\n",
      "[ABC] Iter  9 | Best position: 0.0228 | Minimum value: 0.0005\n",
      "[ABC] Iter 10 | Best position: 0.0228 | Minimum value: 0.0005\n",
      "[ABC] Iter 11 | Best position: 0.0228 | Minimum value: 0.0005\n",
      "[ABC] Iter 12 | Best position: 0.0228 | Minimum value: 0.0005\n",
      "[ABC] Iter 13 | Best position: 0.0228 | Minimum value: 0.0005\n",
      "[ABC] Iter 14 | Best position: -0.0162 | Minimum value: 0.0003\n",
      "[ABC] Iter 15 | Best position: -0.0162 | Minimum value: 0.0003\n",
      "[ABC] Iter 16 | Best position: -0.0162 | Minimum value: 0.0003\n",
      "[ABC] Iter 17 | Best position: 0.0030 | Minimum value: 0.0000\n",
      "[ABC] Iter 18 | Best position: -0.0009 | Minimum value: 0.0000\n",
      "[ABC] Iter 19 | Best position: -0.0009 | Minimum value: 0.0000\n",
      "[ABC] Iter 20 | Best position: -0.0009 | Minimum value: 0.0000\n",
      "\n",
      "ABC Result: Best position = -0.0009, Minimum value = 0.0000\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "\n",
    "# 9. ARTIFICIAL BEE COLONY\n",
    "\n",
    "def fitness(x):\n",
    "    return x**2  # Objective function: minimize x^2\n",
    "\n",
    "# Initialize random solutions (food sources)\n",
    "solutions = [random.uniform(-10, 10) for _ in range(5)]\n",
    "\n",
    "for t in range(20):  # Number of iterations (cycles)\n",
    "    for i in range(len(solutions)):\n",
    "        # Select a random neighbor solution\n",
    "        k = random.randint(0, len(solutions) - 1)\n",
    "\n",
    "        # Generate a new candidate solution\n",
    "        phi = random.uniform(-1, 1)\n",
    "        new_solution = solutions[i] + phi * (solutions[i] - solutions[k])\n",
    "\n",
    "        # Greedy selection: keep the better solution\n",
    "        if fitness(new_solution) < fitness(solutions[i]):\n",
    "            solutions[i] = new_solution\n",
    "\n",
    "    # Find best solution in current population\n",
    "    best = min(solutions, key=fitness)\n",
    "\n",
    "    print(f\"[ABC] Iter {t+1:2d} | Best position: {best:.4f} | Minimum value: {fitness(best):.4f}\")\n",
    "\n",
    "# Final result\n",
    "print(f\"\\nABC Result: Best position = {best:.4f}, Minimum value = {fitness(best):.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "86ea9377-6ef8-408e-b530-0b95b83babb5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
